import { TZDate } from "@date-fns/tz";
import { addMonths, endOfMonth, format, startOfMonth } from "date-fns";
import { es } from "date-fns/locale";
import { firebaseAdmin } from "@/server/firebase/admin";
import { getTenantBySlugFromFirebase } from "@/server/firebase/tenants";
import { ReportesClient } from "./ReportesClient";
export default async function ReportesPage({ params, searchParams }: { params: Promise<{ tenant: string }>; searchParams: Promise<{ month?: string }> }) {
  const { tenant: slug } = await params; const sp = await searchParams; const tenant = await getTenantBySlugFromFirebase(slug); if (!tenant) return null; const now = new TZDate(new Date(), tenant.timezone); const monthISO = sp.month && /^\d{4}-\d{2}$/.test(sp.month) ? sp.month : format(now, "yyyy-MM"); const month = new Date(`${monthISO}-01T12:00:00`); const previous = addMonths(month, -1); const db = firebaseAdmin().db; const ref = db.collection("tenants").doc(tenant.id);
  const [current, previousDocs, clients, staff] = await Promise.all([ref.collection("appointments").where("startsAt", ">=", startOfMonth(month)).where("startsAt", "<=", endOfMonth(month)).orderBy("startsAt").get(), ref.collection("appointments").where("startsAt", ">=", startOfMonth(previous)).where("startsAt", "<=", endOfMonth(previous)).get(), ref.collection("clients").get(), ref.collection("staff").where("active", "==", true).get()]); const completed = current.docs.map((doc) => doc.data()).filter((entry) => entry.status === "completed"); const payments = await Promise.all(completed.map((entry) => ref.collection("appointments").doc(entry.id as string).collection("payments").where("status", "==", "approved").get()));
  const services = new Map<string, number>(); const people = new Map<string, { count: number; photo: string | null }>(); for (const entry of completed) { for (const item of (entry.items ?? []) as { name?: string }[]) services.set(item.name ?? "", (services.get(item.name ?? "") ?? 0) + 1); const name = String(entry.staffName ?? ""); if (name) people.set(name, { count: (people.get(name)?.count ?? 0) + 1, photo: (entry.staffPhoto as string | null) ?? null }); } const income = payments.flatMap((snapshot) => snapshot.docs).reduce((sum, payment) => sum + Number(payment.data().amount ?? 0), 0); const currentClients = new Set(completed.map((entry) => entry.clientId)); const previousClients = new Set(previousDocs.docs.map((doc) => doc.data()).filter((entry) => entry.status === "completed").map((entry) => entry.clientId)); const top = [...people.entries()].sort((a, b) => b[1].count - a[1].count)[0]; const evolution = await Promise.all(Array.from({ length: 6 }).map(async (_, index) => { const date = addMonths(month, index - 5); const docs = await ref.collection("appointments").where("startsAt", ">=", startOfMonth(date)).where("startsAt", "<=", endOfMonth(date)).get(); return { label: format(date, "MMM", { locale: es }), amount: docs.docs.filter((doc) => doc.data().status === "completed").reduce((sum, doc) => sum + Number(doc.data().total ?? 0), 0) }; }));
  return <div className="space-y-lg"><div><h1 className="font-headline-lg-mobile text-headline-lg-mobile text-on-surface">Reportes</h1><p className="font-body-sm text-body-sm text-on-surface-variant capitalize">{format(month, "MMMM yyyy", { locale: es })}</p></div><ReportesClient tenantSlug={slug} monthISO={monthISO} monthOptions={Array.from({ length: 12 }).map((_, index) => { const date = addMonths(now, -index); return { value: format(date, "yyyy-MM"), label: format(date, "MMMM yyyy", { locale: es }) }; })} stats={{ turnosRealizados: completed.length, clientesQueVinieron: currentClients.size, clientesNuevos: clients.docs.filter((doc) => { const created = doc.data().createdAt?.toDate?.(); return created && created >= startOfMonth(month) && created <= endOfMonth(month); }).length, clientesQueNoVolvieron: [...previousClients].filter((id) => !currentClients.has(id)).length, ingresos: income, egresos: 0, ticketMasAlto: completed.reduce((max, entry) => Math.max(max, Number(entry.total ?? 0)), 0), serviciosPopulares: [...services.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([name, count]) => ({ name, count })), evolucionMensual: evolution, profesionalDelMes: staff.size > 1 && top ? { name: top[0], count: top[1].count, photo: top[1].photo } : null }} /></div>;
}
