"use server";
import { revalidatePath } from "next/cache";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { firebaseAdmin } from "@/server/firebase/admin";
import { getCurrentFirebaseUser } from "@/server/firebase/current-user";
import { requireTenantAccess } from "@/server/firebase/tenants";
export type CajaActionState = { error: string | null }; export type ChargeActionState = { error: string | null };
async function access(slug: string) { const user = await getCurrentFirebaseUser(); if (!user) throw new Error("Tu sesión venció. Volvé a iniciar sesión."); return requireTenantAccess(user.uid, slug); }
export async function openCash(tenantSlug: string, _prev: CajaActionState, formData: FormData): Promise<CajaActionState> { try { const { tenant } = await access(tenantSlug); const db = firebaseAdmin().db; const open = await db.collection("tenants").doc(tenant.id).collection("cashSessions").where("closedAt", "==", null).limit(1).get(); if (!open.empty) return { error: "Ya hay una caja abierta" }; const ref = db.collection("tenants").doc(tenant.id).collection("cashSessions").doc(); await ref.create({ id: ref.id, openingAmount: Number(formData.get("openingAmount") ?? 0), openedAt: FieldValue.serverTimestamp(), closedAt: null, expectedAmount: 0, createdAt: FieldValue.serverTimestamp() }); revalidatePath(`/app/${tenantSlug}/caja`); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo abrir la caja" }; } }
export async function closeCash(tenantSlug: string, sessionId: string, _prev: CajaActionState, formData: FormData): Promise<CajaActionState> { try { const { tenant } = await access(tenantSlug); const ref = firebaseAdmin().db.collection("tenants").doc(tenant.id).collection("cashSessions").doc(sessionId); const movements = await ref.collection("movements").get(); const session = (await ref.get()).data(); if (!session || session.closedAt) return { error: "La caja no está abierta" }; const expected = Number(session.openingAmount ?? 0) + movements.docs.reduce((sum, movement) => { const data = movement.data(); return sum + (data.type === "in" ? Number(data.amount) : -Number(data.amount)); }, 0); const counted = Number(formData.get("countedAmount") ?? 0); await ref.update({ closedAt: FieldValue.serverTimestamp(), expectedAmount: expected, countedAmount: counted, difference: counted - expected, differenceReason: String(formData.get("differenceReason") || "") || null }); revalidatePath(`/app/${tenantSlug}/caja`); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo cerrar la caja" }; } }
export async function addCashMovement(tenantSlug: string, sessionId: string, _prev: CajaActionState, formData: FormData): Promise<CajaActionState> { const type = formData.get("type"); const amount = Number(formData.get("amount") ?? 0); if ((type !== "in" && type !== "out") || amount <= 0) return { error: "Ingresá un movimiento válido" }; try { const { tenant } = await access(tenantSlug); const ref = firebaseAdmin().db.collection("tenants").doc(tenant.id).collection("cashSessions").doc(sessionId).collection("movements").doc(); await ref.create({ id: ref.id, type, amount, method: "cash", reason: String(formData.get("reason") || ""), createdAt: FieldValue.serverTimestamp() }); revalidatePath(`/app/${tenantSlug}/caja`); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo registrar el movimiento" }; } }
export async function chargeAppointment(tenantSlug: string, _prev: ChargeActionState, formData: FormData): Promise<ChargeActionState> { const appointmentId = formData.get("appointmentId"); const sessionId = formData.get("sessionId"); const amount = Number(formData.get("amount") ?? 0); const method = formData.get("method"); if (typeof appointmentId !== "string" || typeof method !== "string" || amount <= 0) return { error: "Faltan datos para cobrar" }; try { const { tenant } = await access(tenantSlug); const db = firebaseAdmin().db; const appointmentRef = db.collection("tenants").doc(tenant.id).collection("appointments").doc(appointmentId); const paymentRef = appointmentRef.collection("payments").doc(); await db.runTransaction(async (transaction) => { const appointment = await transaction.get(appointmentRef); if (!appointment.exists) throw new Error("El turno no existe"); const data = appointment.data()!; const balance = Math.max(0, Number(data.balance ?? data.total ?? 0) - amount); transaction.create(paymentRef, { id: paymentRef.id, amount, method, status: "approved", createdAt: Timestamp.now() }); transaction.update(appointmentRef, { balance, status: balance === 0 ? "completed" : data.status, updatedAt: FieldValue.serverTimestamp() });
  // El efectivo cobrado tiene que sumar al arqueo de la caja abierta --
  // antes este cobro solo quedaba en el turno y "Esperado" nunca lo veía.
  if (method === "cash" && typeof sessionId === "string" && sessionId) { const movementRef = db.collection("tenants").doc(tenant.id).collection("cashSessions").doc(sessionId).collection("movements").doc(); transaction.create(movementRef, { id: movementRef.id, type: "in", amount, method, reason: `Cobro turno · ${String(data.clientName ?? "")}`.trim(), appointmentId, createdAt: FieldValue.serverTimestamp() }); } }); revalidatePath(`/app/${tenantSlug}/caja`); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo cobrar el turno" }; } }
