import { TZDate } from "@date-fns/tz";
import { format } from "date-fns";
import { firebaseAdmin } from "@/server/firebase/admin";
import { getTenantBySlugFromFirebase } from "@/server/firebase/tenants";
import { CajaClient } from "./caja-client";

export default async function CajaPage({ params }: PageProps<"/app/[tenant]/caja">) {
  const { tenant: tenantSlug } = await params; const tenant = await getTenantBySlugFromFirebase(tenantSlug); if (!tenant) return null;
  const { db } = firebaseAdmin(); const ref = db.collection("tenants").doc(tenant.id); const today = format(new TZDate(new Date(), tenant.timezone), "yyyy-MM-dd"); const start = new TZDate(`${today}T00:00:00`, tenant.timezone); const end = new TZDate(`${today}T23:59:59.999`, tenant.timezone);
  const [sessions, appointments, products] = await Promise.all([ref.collection("cashSessions").orderBy("openedAt", "desc").get(), ref.collection("appointments").where("startsAt", ">=", start).where("startsAt", "<=", end).orderBy("startsAt").get(), ref.collection("products").where("active", "==", true).get()]);
  const open = sessions.docs.find((doc) => !doc.data().closedAt); const movements = open ? await open.ref.collection("movements").orderBy("createdAt", "desc").get() : null; const lastClosed = sessions.docs.find((doc) => doc.data().closedAt)?.data();
  return <CajaClient tenantSlug={tenantSlug} timezone={tenant.timezone} session={open ? { id: open.id, opened_at: open.data().openedAt?.toDate?.().toISOString?.() ?? new Date().toISOString(), opening_amount: Number(open.data().openingAmount ?? 0) } : null} appointments={appointments.docs.map((doc) => { const item = doc.data(); return { id: doc.id, startsAt: item.startsAt?.toDate?.().toISOString?.() ?? "", total: Number(item.total ?? 0), balance: Number(item.balance ?? 0), clientName: String(item.clientName ?? ""), staffName: String(item.staffName ?? ""), serviceNames: Array.isArray(item.items) ? item.items.map((service: { name?: string }) => service.name ?? "").join(", ") : String(item.serviceName ?? "") }; }).filter((item) => item.balance > 0 && item.startsAt)} products={products.docs.map((doc) => ({ id: doc.id, name: String(doc.data().name ?? ""), price: Number(doc.data().price ?? 0) }))} movements={movements?.docs.map((doc) => ({ id: doc.id, type: String(doc.data().type), amount: Number(doc.data().amount), reason: String(doc.data().reason ?? ""), createdAt: doc.data().createdAt?.toDate?.().toISOString?.() ?? "" })) ?? []} lastClosedSession={lastClosed ? { closedAt: lastClosed.closedAt?.toDate?.().toISOString?.() ?? "", expectedAmount: Number(lastClosed.expectedAmount ?? 0), countedAmount: Number(lastClosed.countedAmount ?? 0), difference: Number(lastClosed.difference ?? 0) } : null} />;
}
