"use server";
import { revalidatePath } from "next/cache";
import { FieldValue } from "firebase-admin/firestore";
import { firebaseAdmin } from "@/server/firebase/admin";
import { getCurrentFirebaseUser } from "@/server/firebase/current-user";
import { requireTenantAccess } from "@/server/firebase/tenants";
export type ConfigActionState = { error: string | null; success?: boolean };
async function tenantForUser(slug: string) { const user = await getCurrentFirebaseUser(); if (!user) throw new Error("Tu sesión venció. Volvé a iniciar sesión."); return requireTenantAccess(user.uid, slug); }
export async function updateBusinessInfo(tenantSlug: string, _prev: ConfigActionState, formData: FormData): Promise<ConfigActionState> { const name = formData.get("name"); if (typeof name !== "string" || name.trim().length < 2) return { error: "Ingresá un nombre válido para el local" }; try { const { tenant } = await tenantForUser(tenantSlug); await firebaseAdmin().db.collection("tenants").doc(tenant.id).update({ name: name.trim(), address: String(formData.get("address") || "") || null, instagramUrl: String(formData.get("instagramUrl") || "") || null, whatsappNumber: String(formData.get("whatsappNumber") || "") || null, updatedAt: FieldValue.serverTimestamp() }); revalidatePath(`/app/${tenantSlug}/configuracion`); return { error: null, success: true }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo actualizar el negocio" }; } }
export async function updateBusinessHours(tenantSlug: string, _prev: ConfigActionState, formData: FormData): Promise<ConfigActionState> { try { const hours = JSON.parse(typeof formData.get("hours") === "string" ? String(formData.get("hours")) : "[]"); if (!Array.isArray(hours)) return { error: "Datos inválidos" }; const valid = hours.every((hour) => typeof hour.weekday === "number" && /^\d{2}:\d{2}$/.test(hour.opens_at) && /^\d{2}:\d{2}$/.test(hour.closes_at)); if (!valid) return { error: "Horarios inválidos" }; const { tenant } = await tenantForUser(tenantSlug); await firebaseAdmin().db.collection("tenants").doc(tenant.id).update({ businessHours: hours.map((hour) => ({ weekday: hour.weekday, opensAt: hour.opens_at, closesAt: hour.closes_at })), updatedAt: FieldValue.serverTimestamp() }); revalidatePath(`/app/${tenantSlug}/configuracion`); return { error: null, success: true }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudieron actualizar los horarios" }; } }
export async function updateDepositSettings(tenantSlug: string, _prev: ConfigActionState, formData: FormData): Promise<ConfigActionState> { const depositType = formData.get("depositType"); const depositValue = Number(formData.get("depositValue") ?? 0); const depositMin = Number(formData.get("depositMin") ?? 0); if (depositType !== "none" && depositType !== "percent" && depositType !== "fixed") return { error: "Tipo de seña inválido" }; try { const { tenant } = await tenantForUser(tenantSlug); await firebaseAdmin().db.collection("tenants").doc(tenant.id).update({ settings: { ...tenant.settings, depositType, depositValue, depositMin }, updatedAt: FieldValue.serverTimestamp() }); revalidatePath(`/app/${tenantSlug}/configuracion`); return { error: null, success: true }; } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo actualizar la seña" }; } }
