"use server";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { firebaseAdmin } from "@/server/firebase/admin";
import { getTenantBySlugFromFirebase } from "@/server/firebase/tenants";
import type { ClientFormData, PublicAppointment, PublicCategory, PublicHold, PublicStaffMember, PublicTenant } from "./types";

const token = () => crypto.randomUUID().replace(/-/g, "");
const key = (staffId: string, instant: Date) => `${staffId}_${instant.toISOString().slice(0, 16).replace(/[-:T]/g, "")}`;
export async function getPublicTenant(slug: string): Promise<PublicTenant | null> { const tenant = await getTenantBySlugFromFirebase(slug); return tenant ? { id: tenant.id, slug: tenant.slug, name: tenant.name, logo_url: (tenant as typeof tenant & { logoUrl?: string | null }).logoUrl ?? null, timezone: tenant.timezone } : null; }
export async function getPublicCatalog(tenantId: string): Promise<PublicCategory[]> { const docs = await firebaseAdmin().db.collection("tenants").doc(tenantId).collection("services").where("active", "==", true).get(); return [{ id: "services", name: "Servicios", services: docs.docs.filter((doc) => !doc.data().archivedAt).map((doc) => { const data = doc.data(); return { id: doc.id, name: data.name, description: null, price: Number(data.price), duration: (data.phases ?? []).reduce((sum: number, phase: { minutes?: number }) => sum + Number(phase.minutes ?? 0), Number(data.bufferAfterMin ?? 0)) }; }) }]; }
export async function getPublicStaff(tenantId: string): Promise<PublicStaffMember[]> { const docs = await firebaseAdmin().db.collection("tenants").doc(tenantId).collection("staff").where("active", "==", true).get(); return docs.docs.map((doc) => ({ id: doc.id, name: String(doc.data().displayName) })); }
export async function getPublicStaffForService(tenantId: string, serviceId: string): Promise<PublicStaffMember[]> { const staff = await getPublicStaff(tenantId); const db = firebaseAdmin().db; const matches = await Promise.all(staff.map(async (person) => ({ person, doc: await db.collection("tenants").doc(tenantId).collection("staff").doc(person.id).get() }))); return matches.filter(({ doc }) => (doc.data()?.serviceIds ?? []).includes(serviceId)).map(({ person }) => person); }
export async function getAvailableSlots(tenantId: string, serviceId: string, staffId: string | "any", dateISO: string, timezone: string, allStaffIds: string[]) { const db = firebaseAdmin().db; const service = await db.collection("tenants").doc(tenantId).collection("services").doc(serviceId).get(); if (!service.exists) return []; const duration = (service.data()?.phases ?? []).reduce((sum: number, phase: { minutes?: number }) => sum + Number(phase.minutes ?? 0), Number(service.data()?.bufferAfterMin ?? 0)); const tenant = await db.collection("tenants").doc(tenantId).get(); const hours = (tenant.data()?.businessHours ?? []).filter((hour: { weekday: number }) => hour.weekday === new Date(`${dateISO}T12:00:00`).getDay()); if (!hours.length) return []; const ids = staffId === "any" ? allStaffIds : [staffId]; const candidates: string[] = []; for (const hour of hours) { for (let minute = Number(hour.opensAt.slice(0, 2)) * 60 + Number(hour.opensAt.slice(3)); minute + duration <= Number(hour.closesAt.slice(0, 2)) * 60 + Number(hour.closesAt.slice(3)); minute += Number(tenant.data()?.settings?.slotIntervalMin ?? 15)) { const start = new Date(`${dateISO}T00:00:00`); start.setUTCHours(Math.floor(minute / 60), minute % 60, 0, 0); const keys = Array.from({ length: Math.ceil(duration / 15) }, (_, index) => key("", new Date(start.getTime() + index * 900000)).slice(1)); const available = await Promise.all(ids.map(async (id) => { const snapshots = await Promise.all(keys.map((slot) => db.collection("tenants").doc(tenantId).collection("occupancy").doc(`${id}_${slot}`).get())); return snapshots.some((snapshot) => !snapshot.exists || snapshot.data()?.expiresAt?.toDate?.() < new Date()); })); if (available.some(Boolean)) candidates.push(start.toISOString()); } } return [...new Set(candidates)].sort(); }
export async function createHold(tenantId: string, serviceId: string, staffId: string | "any", allStaffIds: string[], startsAtISO: string, _dateISO: string, _timezone: string): Promise<PublicHold> { const db = firebaseAdmin().db; const tenantRef = db.collection("tenants").doc(tenantId); const service = await tenantRef.collection("services").doc(serviceId).get(); if (!service.exists) throw new Error("Servicio no encontrado"); const start = new Date(startsAtISO); const duration = (service.data()?.phases ?? []).reduce((sum: number, phase: { minutes?: number }) => sum + Number(phase.minutes ?? 0), Number(service.data()?.bufferAfterMin ?? 0)); const staffIds = staffId === "any" ? allStaffIds : [staffId]; const holdRef = tenantRef.collection("holds").doc(); let selected = ""; await db.runTransaction(async (transaction) => { for (const candidate of staffIds) { const slots = Array.from({ length: Math.ceil(duration / 15) }, (_, index) => tenantRef.collection("occupancy").doc(key(candidate, new Date(start.getTime() + index * 900000)))); const existing = await Promise.all(slots.map((slot) => transaction.get(slot))); if (existing.some((doc) => doc.exists && doc.data()?.expiresAt?.toDate?.() > new Date())) continue; selected = candidate; const expiresAt = Timestamp.fromDate(new Date(Date.now() + 10 * 60000)); slots.forEach((slot) => transaction.set(slot, { holdId: holdRef.id, expiresAt })); transaction.set(holdRef, { id: holdRef.id, tenantId, staffId: selected, serviceId, startsAt: Timestamp.fromDate(start), endsAt: Timestamp.fromDate(new Date(start.getTime() + duration * 60000)), expiresAt, createdAt: FieldValue.serverTimestamp() }); break; } if (!selected) throw new Error("Ese horario ya no está disponible"); }); const hold = (await holdRef.get()).data()!; return { id: holdRef.id, tenant_id: tenantId, staff_id: selected, starts_at: hold.startsAt.toDate().toISOString(), ends_at: hold.endsAt.toDate().toISOString(), expires_at: hold.expiresAt.toDate().toISOString() }; }
export async function confirmHold(holdId: string, client: ClientFormData): Promise<PublicAppointment> { const db = firebaseAdmin().db; const holds = await db.collectionGroup("holds").where("id", "==", holdId).limit(1).get(); if (holds.empty) throw new Error("La reserva venció"); const holdRef = holds.docs[0].ref; const hold = holds.docs[0].data(); if (hold.expiresAt.toDate() < new Date()) throw new Error("La reserva venció"); const tenantRef = holdRef.parent.parent!; const appointmentRef = tenantRef.collection("appointments").doc(); const appointmentToken = token(); await db.runTransaction(async (transaction) => { const latest = await transaction.get(holdRef); if (!latest.exists || latest.data()!.expiresAt.toDate() < new Date()) throw new Error("La reserva venció"); const service = await transaction.get(tenantRef.collection("services").doc(hold.serviceId)); transaction.set(appointmentRef, { id: appointmentRef.id, token: appointmentToken, tenantId: hold.tenantId, staffId: hold.staffId, clientName: client.full_name, clientPhone: client.phone_e164, clientEmail: client.email || null, startsAt: hold.startsAt, endsAt: hold.endsAt, status: "confirmed", total: Number(service.data()?.price ?? 0), balance: Number(service.data()?.price ?? 0), items: [{ name: service.data()?.name ?? "Servicio" }], createdAt: FieldValue.serverTimestamp() }); transaction.delete(holdRef); }); return { id: appointmentRef.id, token: appointmentToken, status: "confirmed", starts_at: hold.startsAt.toDate().toISOString(), ends_at: hold.endsAt.toDate().toISOString(), total: Number((await tenantRef.collection("services").doc(hold.serviceId).get()).data()?.price ?? 0), balance: Number((await tenantRef.collection("services").doc(hold.serviceId).get()).data()?.price ?? 0) }; }
